[33mWARNING [0m root:utils.py:15 Request failed: Connection error. Retrying... (1/3)
[33mWARNING [0m root:utils.py:15 Request failed: Connection error. Retrying... (2/3)
[33mWARNING [0m root:utils.py:15 Request failed: Connection error. Retrying... (3/3)
[31mCRITICAL[0m root:utils.py:23 Request failed after 3 attempts.