{"name": "test_not_found_response", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "@pytest.mark.xfail\n    def test_not_found_response():\n        response = requests.get(\"http://localhost:8080/api/unknown\")\n>       assert response.status_code == 200 #404\nE       assert 404 == 200\nE        +  where 404 = <Response [404]>.status_code\n\nsrc/pytestify/tests/sample_test.py:34: AssertionError"}, "attachments": [{"name": "log", "source": "be301155-7710-4940-ac6a-f60883ec1fb1-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c971ffb9-e1b4-4d29-aed5-302a46e7e7d7-attachment.txt", "type": "text/plain"}], "start": 1725191451052, "stop": 1725191451138, "uuid": "cadcb88a-7c8f-4d29-acd5-ee9ec0262518", "historyId": "5759dc2125368ad4ccd2c19e8563350e", "testCaseId": "5759dc2125368ad4ccd2c19e8563350e", "fullName": "src.pytestify.tests.sample_test#test_not_found_response", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "src.pytestify.tests"}, {"name": "suite", "value": "sample_test"}, {"name": "host", "value": "BMDVJAVEDAN"}, {"name": "thread", "value": "2789-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.pytestify.tests.sample_test"}]}