{"name": "test_not_found_response", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "@pytest.mark.xfail\n    def test_not_found_response():\n        response = requests.get(\"http://localhost:8080/api/unknown\")\n>       assert response.status_code == 200 #404\nE       assert 404 == 200\nE        +  where 404 = <Response [404]>.status_code\n\nsrc/pytestify/tests/sample_test.py:34: AssertionError"}, "attachments": [{"name": "log", "source": "a9f0b0f3-900a-463f-b578-33fe7394237d-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "bb08af45-f3fb-4968-a4f4-f0fd6ad4a0bf-attachment.txt", "type": "text/plain"}], "start": 1725191660525, "stop": 1725191660609, "uuid": "12a24749-35c4-48ec-a19a-02eb5032e749", "historyId": "5759dc2125368ad4ccd2c19e8563350e", "testCaseId": "5759dc2125368ad4ccd2c19e8563350e", "fullName": "src.pytestify.tests.sample_test#test_not_found_response", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "src.pytestify.tests"}, {"name": "suite", "value": "sample_test"}, {"name": "host", "value": "BMDVJAVEDAN"}, {"name": "thread", "value": "3039-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.pytestify.tests.sample_test"}]}