{"name": "test_not_found_response", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "@pytest.mark.xfail\n    def test_not_found_response():\n        response = requests.get(\"http://localhost:8080/api/unknown\")\n>       assert response.status_code == 200 #404\nE       assert 404 == 200\nE        +  where 404 = <Response [404]>.status_code\n\nsrc/pytestify/tests/sample_test.py:34: AssertionError"}, "attachments": [{"name": "log", "source": "6cbd04de-5218-4acc-9ecc-d90b029b16c4-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "1bbab65c-9d34-48b9-abda-8c10ce4fce3c-attachment.txt", "type": "text/plain"}], "start": 1725187814488, "stop": 1725187814575, "uuid": "7788ede6-3289-4321-a2ec-1c8eb7d4f01a", "historyId": "5759dc2125368ad4ccd2c19e8563350e", "testCaseId": "5759dc2125368ad4ccd2c19e8563350e", "fullName": "src.pytestify.tests.sample_test#test_not_found_response", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "src.pytestify.tests"}, {"name": "suite", "value": "sample_test"}, {"name": "host", "value": "BMDVJAVEDAN"}, {"name": "thread", "value": "97709-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.pytestify.tests.sample_test"}]}