[31m[1mERROR   [0m root:utils.py:19 Base URL or endpoint is None