{"name": "test_not_found_response", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "@pytest.mark.xfail\n    def test_not_found_response():\n        response = requests.get(\"http://localhost:8080/api/unknown\")\n>       assert response.status_code == 200 #404\nE       assert 404 == 200\nE        +  where 404 = <Response [404]>.status_code\n\nsrc/pytestify/tests/sample_test.py:34: AssertionError"}, "attachments": [{"name": "log", "source": "9b780b9b-a711-402d-b21e-5379ecc0bf7d-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "52ab26b1-faf9-412c-9e99-10c542d66fd5-attachment.txt", "type": "text/plain"}], "start": 1725188263259, "stop": 1725188263348, "uuid": "a9628923-3d83-48fd-8e5c-8c003e9b6b0d", "historyId": "5759dc2125368ad4ccd2c19e8563350e", "testCaseId": "5759dc2125368ad4ccd2c19e8563350e", "fullName": "src.pytestify.tests.sample_test#test_not_found_response", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "src.pytestify.tests"}, {"name": "suite", "value": "sample_test"}, {"name": "host", "value": "BMDVJAVEDAN"}, {"name": "thread", "value": "98079-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.pytestify.tests.sample_test"}]}