{"name": "test_not_found_response", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "@pytest.mark.xfail\n    def test_not_found_response():\n        response = requests.get(\"http://localhost:8080/api/unknown\")\n>       assert response.status_code == 200 #404\nE       assert 404 == 200\nE        +  where 404 = <Response [404]>.status_code\n\nsrc/pytestify/tests/sample_test.py:34: AssertionError"}, "attachments": [{"name": "log", "source": "d55e77a6-c190-43ba-bfa0-8912d1a10fbf-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "a8d48b1b-a120-4c0c-a36d-3c1e7ee3538c-attachment.txt", "type": "text/plain"}], "start": 1725192135053, "stop": 1725192135139, "uuid": "d372f2a8-fb4d-4ee3-9e06-e58b659455a3", "historyId": "5759dc2125368ad4ccd2c19e8563350e", "testCaseId": "5759dc2125368ad4ccd2c19e8563350e", "fullName": "src.pytestify.tests.sample_test#test_not_found_response", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "src.pytestify.tests"}, {"name": "suite", "value": "sample_test"}, {"name": "host", "value": "BMDVJAVEDAN"}, {"name": "thread", "value": "3275-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.pytestify.tests.sample_test"}]}