{"uuid": "479afff6-5400-4d66-913b-0f1f9acd6a07", "children": ["529284e2-7c46-496a-bc11-fe111e4ba89c", "d1d22225-3077-4efe-825a-33b881452ccf", "2f04ef6d-dbbb-4853-ad81-8297fb224f9a", "3e2ca31e-d9a5-47b6-b692-1295f8babcb2", "71f6a9ca-f665-4770-93d2-0c89aa05a17e", "9dcce2ad-e9b5-40ba-b459-fb20fb7b66ce"], "befores": [{"name": "start_wiremock", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'docker-compose'\n", "trace": "  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/ja/IdeaProjects/PyTestify/src/pytestify/tests/conftest.py\", line 47, in start_wiremock\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 548, in run\n    with Popen(*popenargs, **kwargs) as process:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 1026, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 1955, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\n"}, "start": 1725190764645, "stop": 1725190764645}], "start": 1725190764644, "stop": 1725190765332}